apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
  labels:
    app: flask-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
        - name: flask-webapp
          image: sintosm/flask-webapp:latest
          ports:
            - containerPort: 5000
